[ml2_type_vlan]
network_vlan_ranges = {% for bridge in neutron_bridge_name.split(',') %}physnet{{ loop.index0 + 1 }}{% if bridge in ml2_network_vlan_ranges %}:{{ml2_network_vlan_ranges.get(bridge)}}{% endif %}{% if not loop.last %},{% endif %}{% endfor %}

[ovn]
# TODO
dns_servers = 10.14.0.10
