[DEFAULT]
enabled_network_interfaces=noop,flat,neutron
default_network_interface=neutron

[neutron]
cleaning_network = ironic-provisioning
provisioning_network = ironic-provisioning
# provisioning_network_security_groups

[pxe]
tftp_server = {{ironic_http_interface_address}}

