[trust]
cluster_user_trust = True

[cluster_template]
kubernetes_allowed_network_drivers = calico,cilium,unspecified
kubernetes_default_network_driver = calico

[nova_client]
# fix for Server group feature in magnum_cluster_api 0.24.0
# https://bugs.launchpad.net/magnum/+bug/2067345
api_version = 2.15
