---
- hosts: all
  name: Set Prerequisites
  gather_facts: true
  tasks:
    - name: Remove loopback entry for hostname
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127[0-9.]+\s+{{ansible_hostname}}'
        state: absent
    - name: Ensure hostname points to default IPv4 address
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^.*\\b{{ ansible_hostname }}\\b.*"
        line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
        state: present
        backup: true
- hosts: all
  gather_facts: yes
  environment:
    PATH: "/lib/systemd:/usr/lib/systemd:{{ ansible_env.PATH }}"
  roles:
    - role: debops.debops.resources
    - role: debops.debops.ntp
  post_tasks:
    - name: 'Restart nftables'
      service:
        name: nftables
        enabled: true
        state: restarted
    - name: Enable bridge forwarding service
      ansible.builtin.systemd:
        name: wrx-bridge-forwarding.service
        enabled: true
        daemon_reload: true
- hosts: all
  gather_facts: yes
  roles:
    - role: lae.proxmox
