---
ansible_python_interpreter: "{{ lookup('env', 'VIRTUAL_ENV') }}/bin/python"

project_name:        "automation_by_ansible"
project_description: "Project created via Ansible"
network_name:        "private"
subnet_name:         "private-subnet"
subnet_cidr:         "192.168.10.0/24"
router_name:         "router"
public_network:      "shared3010"
flavor_name:         "m1.small"
image_name:          "ubuntu-24.04"
key_name:            "my_ssh_key"
server_name:         "vm01"
volume_name:         "vol-vm01"
volume_size:         20
