---
enable_central_logging: "false"
enable_fluentd:         "false"
# enable_prometheus_elasticsearch_exporter: "yes"
# opensearch_soft_retention_period_days: "2"
# opensearch_hard_retention_period_days: "3"
