#!/usr/bin/env bash
##############################################################################
# config
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
CONFIG_DIR="$SCRIPT_DIR/../conf/"
ENV_CONF="$CONFIG_DIR/env.yaml"

##############################################################################
# vars
ID_START_FROM=1000
TEMPLATE_ID=9000
#STORAGE="local-lvm"
STORAGE="local"
# STORAGE="vmdata"
NCARD_MODEL="virtio"
SNIPPET_STORAGE="local"
SNIPPET_DIR="/var/lib/vz/snippets"
IFACE_DATA_JSON=$(cat "$ENV_CONF" | yq -r '.network_conf' -j)
NAMESERVER=$(   cat $ENV_CONF | yq -r '.resolve_conf.nameservers[]'   | xargs)
SEARCHDOMAIN=$( cat $ENV_CONF | yq -r '.resolve_conf.searchdomains[]' | xargs)
CIUSER=deploy
CIPASS=deploy

mkdir -p "$SNIPPET_DIR"

if [[ ! -f "$ENV_CONF" ]]; then
    echo "Error: Configuration file $ENV_CONF not found."
    exit 1
fi
##############################################################################
# args
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --id)        ID="$2";           shift 2 ;;
        --name)      NAME="$2";         shift 2 ;;
        --cpu)       CPU="$2";          shift 2 ;;
        --ram)       RAM="$2";          shift 2 ;;
        --disks)     DISKS_JSON="$2";   shift 2 ;;
        --netconf)   NETCONF_JSON="$2"; shift 2 ;;
        --command)   COMMAND="$2";      shift 2 ;;
        --airgapped) AIRGAPPED="$2";    shift 2 ;;

        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
done

VMID=$(($ID_START_FROM + ID))
DOMAIN=${NAME#*.}
SEARCHDOMAIN="$SEARCHDOMAIN $DOMAIN"

##############################################################################
# go
VENDOR_FILE="$SNIPPET_DIR/vm-${VMID}-vendor.yaml"
# VENDOR_FILE="$SNIPPET_DIR/vm-${VMID}-vendor.yaml.debug"

qm clone $TEMPLATE_ID $VMID --name "$NAME" --storage $STORAGE --full
qm set $VMID --ciuser $CIUSER --cipassword $CIPASS --cores "$CPU" --memory "$RAM"

cat <<EOF > "$VENDOR_FILE"
#cloud-config
bootcmd:
EOF

if [[ "$AIRGAPPED" =~ ^(true|yes|soft)$ ]]
  then
  cat <<EOF >> "$VENDOR_FILE"
  - |
    cat > /etc/netplan/60-eth0-override.yaml <<EOF
    network:
      version: 2
      ethernets:
        eth0:
          activation-mode: off
    EOF
EOF
fi

#
# NOTE: at this stage we only create netplan config file to rename interfaces
#       it remains deactivated and will be applied later
#
cat <<EOF >> "$VENDOR_FILE"
  - |
    cat > /etc/netplan/70-wrx-rename-ifaces.yaml.off <<EOF
    network:
      version: 2
      ethernets:
EOF

# Iterate through the requested network interfaces
while IFS=$'\t' read -r NET_NAME MACADDR IP GW MTU; do

  # Get slot ID
  NEXT_ID=0
  while qm config "$VMID" | grep -q "net$NEXT_ID:"; do
      ((NEXT_ID++))
  done

  # Lookup 'iface' dynamically from the JSON we got via yq
  HEX_OCTET=$(echo "$MACADDR" | cut -d':' -f5)
  IDX=$((16#$HEX_OCTET))
  NET_KEY=$(echo "$IFACE_DATA_JSON" | jq -r "to_entries | sort_by(.key) | .[$IDX].key")

  TARGET_IFACE=$(echo "$IFACE_DATA_JSON" | jq -r ".\"$NET_KEY\".iface // \"\"")

  qm set $VMID --net$NEXT_ID "$NCARD_MODEL,bridge=br$NET_NAME,macaddr=$MACADDR${MTU:+,mtu=$MTU}"
  if [ -n "$IP" ]; then
      qm set $VMID --ipconfig$NEXT_ID "ip=${IP}${GW:+,gw=$GW}"
  fi

  if [[ -n "$TARGET_IFACE" && -n "$MACADDR" ]]; then
      cat <<EOF >> "$VENDOR_FILE"
        eth${NEXT_ID}:
          match:
            macaddress: "${MACADDR,,}"
          set-name: "$TARGET_IFACE"
          dhcp4: false
          dhcp6: false
          link-local: []
EOF
    fi
done < <(echo "$NETCONF_JSON" | jq -r 'to_entries[] | "\(.key)\t\(.value.macaddr // "")\t\(.value.ip // "")\t\(.value.gw // "")\t\(.value.mtu // "")"')

cat <<EOF >> "$VENDOR_FILE"
    EOF
  - chmod 600 /etc/netplan/*.yaml
  - netplan generate
  - systemctl restart systemd-networkd
EOF


# TODO: do we need this
# if [[ "$AIRGAPPED" =~ ^(soft)$ ]]
#   then
#   cat <<EOF >> "$VENDOR_FILE"
# proxy:       http://proxy.wrx.sckt.net:3128
# https_proxy: http://proxy.wrx.sckt.net:3128
# no_proxy:    localhost,127.0.0.1,.wrx.sckt.net,169.254.169.254
# EOF
# fi

if [[ "$AIRGAPPED" =~ ^(true|yes|soft)$ ]]
  then
  #
  # NOTE: this is needed for cloud-init during provisioning to
  #         - update OS
  #         - install packages
  #
  cat <<EOF >> "$VENDOR_FILE"
apt:
  proxy: http://proxy.wrx.sckt.net:3128
EOF
fi

cat <<EOF >> "$VENDOR_FILE"
package_udpate: true
packages:
  - curl
  - docker-ce
  - git
  - htop
  - httping
  - jq
  - net-tools
  - ngrep
  - nmap
  - python3-venv
  - screen
  - tcpdump
  - tree
  - vim
  - wget
  - yq
manage_etc_hosts: true
runcmd:
  - growpart  /dev/sda  1
  - resize2fs /dev/sda1
  - touch /etc/cloud/cloud-init.disabled
  - mv /etc/netplan/70-wrx-rename-ifaces.yaml.off /etc/netplan/70-wrx-rename-ifaces.yaml
  - netplan apply
  - systemctl restart systemd-timesyncd
EOF


if [ -n "$COMMAND" ]
  then
cat <<EOF >> "$VENDOR_FILE"
  - "$COMMAND"
EOF
fi


cat <<EOF >> "$VENDOR_FILE"
fs_setup:
  - device:     /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
    filesystem: ext4
    overwrite:  true
mounts:
  - [ /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1, /var/lib/docker, "ext4", "defaults,nofail", "0", "2" ]
write_files:
  - path:        /etc/systemd/timesyncd.conf
    owner:       root:root
    permissions: '0644'
    content: |
      [Time]
      NTP=10.14.0.19
  - path:        /etc/vim/vimrc.local
    owner:       root:root
    permissions: '0644'
    content:     "set paste"
  - path:        /etc/docker/daemon.json
    owner:       root:root
    permissions: '0644'
    content: |
      {
        "insecure-registries": ["registry.services.wrx.sckt.net",   "registry.wrx.sckt.net"]
      }
  - path:        /etc/apt/keyrings/docker.asc
    owner:       root:root
    permissions: '0644'
    content: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
      lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
      38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
      L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
      UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
      cmhh4HgeQscQHYgOJjjDVfoY5MucvglbIgCqfzAHW9jxmRL4qbMZj+b1XoePEtht
      ku4bIQN1X5P07fNWzlgaRL5Z4POXDDZTlIQ/El58j9kp4bnWRCJW0lya+f8ocodo
      vZZ+Doi+fy4D5ZGrL4XEcIQP/Lv5uFyf+kQtl/94VFYVJOleAv8W92KdgDkhTcTD
      G7c0tIkVEKNUq48b3aQ64NOZQW7fVjfoKwEZdOqPE72Pa45jrZzvUFxSpdiNk2tZ
      XYukHjlxxEgBdC/J3cMMNRE1F4NCA3ApfV1Y7/hTeOnmDuDYwr9/obA8t016Yljj
      q5rdkywPf4JF8mXUW5eCN1vAFHxeg9ZWemhBtQmGxXnw9M+z6hWwc6ahmwARAQAB
      tCtEb2NrZXIgUmVsZWFzZSAoQ0UgZGViKSA8ZG9ja2VyQGRvY2tlci5jb20+iQI3
      BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEI2BgDwO
      v82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmqvMqd
      tI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3Lgk
      jonyUf9bwtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m
      6fqcd5Fu7pxsqm0EUDK5NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9P
      XRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8OYBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMc
      FYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4DQJjbxeMZbiNMG5kGECA8
      g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSFbzwKB0Jm
      ebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh
      9svIGfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5
      G34Ct5RS7Jt6LIfFdtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoW
      FPIZ7d6vH+Vro6xuWEGiuMaiznap2KhZmpkgfupyFmplh0s6knymuQINBFit2ioB
      EADneL9S9m4vhU3blaRjVUUyJ7b/qTjcSylvCH5XUE6R2k+ckEZjfAMZPLpO+/tF
      M2JIJMD4SifKuS3xck9KtZGCufGmcwiLQRzeHF7vJUKrLD5RTkNi23ydvWZgPjtx
      Q+DTT1Zcn7BrQFY6FgnRoUVIxwtdw1bMY/89rsFgS5wwuMESd3Q2RYgb7EOFOpnu
      w6da7WakWf4IhnF5nsNYGDVaIHzpiqCl+uTbf1epCjrOlIzkZ3Z3Yk5CM/TiFzPk
      z2lLz89cpD8U+NtCsfagWWfjd2U3jDapgH+7nQnCEWpROtzaKHG6lA3pXdix5zG8
      eRc6/0IbUSWvfjKxLLPfNeCS2pCL3IeEI5nothEEYdQH6szpLog79xB9dVnJyKJb
      VfxXnseoYqVrRz2VVbUI5Blwm6B40E3eGVfUQWiux54DspyVMMk41Mx7QJ3iynIa
      1N4ZAqVMAEruyXTRTxc9XW0tYhDMA/1GYvz0EmFpm8LzTHA6sFVtPm/ZlNCX6P1X
      zJwrv7DSQKD6GGlBQUX+OeEJ8tTkkf8QTJSPUdh8P8YxDFS5EOGAvhhpMBYD42kQ
      pqXjEC+XcycTvGI7impgv9PDY1RCC1zkBjKPa120rNhv/hkVk/YhuGoajoHyy4h7
      ZQopdcMtpN2dgmhEegny9JCSwxfQmQ0zK0g7m6SHiKMwjwARAQABiQQ+BBgBCAAJ
      BQJYrdoqAhsCAikJEI2BgDwOv82IwV0gBBkBCAAGBQJYrdoqAAoJEH6gqcPyc/zY
      1WAP/2wJ+R0gE6qsce3rjaIz58PJmc8goKrir5hnElWhPgbq7cYIsW5qiFyLhkdp
      YcMmhD9mRiPpQn6Ya2w3e3B8zfIVKipbMBnke/ytZ9M7qHmDCcjoiSmwEXN3wKYI
      mD9VHONsl/CG1rU9Isw1jtB5g1YxuBA7M/m36XN6x2u+NtNMDB9P56yc4gfsZVES
      KA9v+yY2/l45L8d/WUkUi0YXomn6hyBGI7JrBLq0CX37GEYP6O9rrKipfz73XfO7
      JIGzOKZlljb/D9RX/g7nRbCn+3EtH7xnk+TK/50euEKw8SMUg147sJTcpQmv6UzZ
      cM4JgL0HbHVCojV4C/plELwMddALOFeYQzTif6sMRPf+3DSj8frbInjChC3yOLy0
      6br92KFom17EIj2CAcoeq7UPhi2oouYBwPxh5ytdehJkoo+sN7RIWua6P2WSmon5
      U888cSylXC0+ADFdgLX9K2zrDVYUG1vo8CX0vzxFBaHwN6Px26fhIT1/hYUHQR1z
      VfNDcyQmXqkOnZvvoMfz/Q0s9BhFJ/zU6AgQbIZE/hm1spsfgvtsD1frZfygXJ9f
      irP+MSAI80xHSf91qSRZOj4Pl3ZJNbq4yYxv0b1pkMqeGdjdCYhLU+LZ4wbQmpCk
      SVe2prlLureigXtmZfkqevRz7FrIZiu9ky8wnCAPwC7/zmS18rgP/17bOtL4/iIz
      QhxAAoAMWVrGyJivSkjhSGx1uCojsWfsTAm11P7jsruIL61ZzMUVE2aM3Pmj5G+W
      9AcZ58Em+1WsVnAXdUR//bMmhyr8wL/G1YO1V3JEJTRdxsSxdYa4deGBBY/Adpsw
      24jxhOJR+lsJpqIUeb999+R8euDhRHG9eFO7DRu6weatUJ6suupoDTRWtr/4yGqe
      dKxV3qQhNLSnaAzqW/1nA3iUB4k7kCaKZxhdhDbClf9P37qaRW467BLCVO/coL3y
      Vm50dwdrNtKpMBh3ZpbB1uJvgi9mXtyBOMJ3v8RZeDzFiG8HdCtg9RvIt/AIFoHR
      H3S+U79NT6i0KPzLImDfs8T7RlpyuMc4Ufs8ggyg9v3Ae6cN3eQyxcK3w0cbBwsh
      /nQNfsA6uu+9H7NhbehBMhYnpNZyrHzCmzyXkauwRAqoCbGCNykTRwsur9gS41TQ
      M8ssD1jFheOJf3hODnkKU+HKjvMROl1DK7zdmLdNzA1cvtZH/nCC9KPj1z8QC47S
      xx+dTZSx4ONAhwbS/LN3PoKtn8LPjY9NP9uDWI+TWYquS2U+KHDrBDlsgozDbs/O
      jCxcpDzNmXpWQHEtHU7649OXHP7UeNST1mCUCH5qdank0V1iejF6/CfTFU4MfcrG
      YT90qFF93M3v01BbxP+EIY2/9tiIPbrd
      =0YYh
      -----END PGP PUBLIC KEY BLOCK-----
  - path:        /etc/apt/sources.list.d/docker.sources
    owner:       root:root
    permissions: '0644'
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: noble
      Components: stable
      Signed-by: /etc/apt/keyrings/docker.asc
  - path:        /etc/apt/preferences.d/docker-pin
    owner:       root:root
    permissions: '0644'
    content: |
      Package: docker-ce
      Pin: version 5:28.*
      Pin-Priority: 1001

      Package: docker-ce-cli
      Pin: version 5:28.*
      Pin-Priority: 1001
  - path:        /etc/env.json
    owner:       root:root
    permissions: '0644'
    content: |
      {
        "id":        $ID,
        "vmid":      $VMID,
        "name":      "$NAME",
        "cpu":       $CPU,
        "ram":       $RAM,
        "disks":     $DISKS_JSON,
        "netconf":   $NETCONF_JSON,
        "airgapped": "$AIRGAPPED"
      }
EOF

if [ "$AIRGAPPED" = "soft" ]
  then
  cat <<EOF >> "$VENDOR_FILE"
  - path:        /etc/profile.d/proxy.sh
    owner:       root:root
    permissions: '0644'
    content: |
      export http_proxy="http://proxy.wrx.sckt.net:3128"
      export https_proxy="http://proxy.wrx.sckt.net:3128"
      export no_proxy="localhost,127.0.0.1,.wrx.sckt.net,169.254.169.254"
      export HTTP_PROXY="http://proxy.wrx.sckt.net:3128"
      export HTTPS_PROXY="http://proxy.wrx.sckt.net:3128"
      export NO_PROXY="localhost,127.0.0.1,.wrx.sckt.net,169.254.169.254"
EOF
fi

cat <<EOF >> "$VENDOR_FILE"
  - path:        /etc/profile.d/wrx.sh
    owner:       root:root
    permissions: '0644'
    content: |
      export WRX_RAW_BASE_PATH=https://raw.githack.com/codecap/openstack-workshop/main
      export WRX_PROXY=http://proxy.wrx.sckt.net:3128
      export WRX_INFRA_NODES_GR1="dns|proxy|registry"
      export WRX_INFRA_NODES_GR2="deployment|recorder"
EOF

#
# NOTE: whether or not we wrote in a debug file with ".debug" suffix we use
#       the file without it
#
qm set $VMID --cicustom "vendor=${SNIPPET_STORAGE}:snippets/$(basename ${VENDOR_FILE/.debug/})"
qm cloudinit update $VMID

# Disks logic (Original Loop)
while read SIZE; do
    D_ID=0
    while qm config "$VMID" | grep -q "scsi$D_ID:"; do
        ((D_ID++))
    done
    qm set "$VMID" "--scsi$D_ID" "${STORAGE}:${SIZE}"
done < <(echo "$DISKS_JSON" | jq -Mr ".[]")

##############################################################################
# post steps

# Clear nameservers and search domain
qm set $VMID --nameserver   "$NAMESERVER"
qm set $VMID --searchdomain "$SEARCHDOMAIN"

# ssh keys
qm set $VMID --sshkeys <(cat ~/.ssh/authorized_keys;)

# resize the root disk
qm resize $VMID scsi0 16G

# cpu type
qm set $VMID --cpu host

# set autostart
qm set $VMID --onboot 1

# start
qm start $VMID
