#!/usr/bin/env bash
##############################################################################
# config
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
CONFIG_DIR="$SCRIPT_DIR/../conf/"
ENV_CONF="$CONFIG_DIR/env.yaml"

##############################################################################
# vars

##############################################################################
# functions

##############################################################################
# go

qm list | awk '{print $1" "$2}' | grep -E "^1[0-9]{3}" | while read -r VMID NAME; do
    STATUS=$(qm status "$VMID" | awk '{print $2}')

    if [ "$STATUS" == "running" ]; then
        echo "qm stop $VMID # $NAME"
    fi
    echo "qm destroy "$VMID" --purge --destroy-unreferenced-disks # $NAME"
done
