[global]
osd_pool_default_pg_num   = 32
osd_pool_default_pgp_num  = 1
osd_pool_default_size     = 3
osd_pool_default_min_size = 1
mon_max_pg_per_osd        = 1024
# max_open_files            = 131072

[osd]
filestore_queue_max_bytes = 1048576000
filestore_queue_max_ops   = 50000
# osd_crush_initial_weight  = 0
# osd_op_threads            = 16
# osd_disk_threads          = 4

[mon]
mon_compact_on_start                  = true
mon_osd_down_out_subtree_limit        = host
auth_allow_insecure_global_id_reclaim = false

[mgr]
# https://docs.ceph.com/en/latest/cephadm/services/monitoring/#using-custom-images
# mgr/cephadm/container_image_prometheus    = registry.mgmt.tst.sckt.net/prometheus/prometheus:v2.43.0
# mgr/cephadm/container_image_node_exporter = registry.mgmt.tst.sckt.net/prometheus/node-exporter:v1.5.0
# mgr/cephadm/container_image_grafana       = registry.mgmt.tst.sckt.net/ceph/ceph-grafana:9.4.7
# mgr/cephadm/container_image_alertmanager  = registry.mgmt.tst.sckt.net/prometheus/alertmanager:v0.25.0
# mgr/cephadm/container_image_haproxy       = registry.mgmt.tst.sckt.net/ceph/haproxy:2.3
# mgr/cephadm/container_image_keepalived    = registry.mgmt.tst.sckt.net/ceph/keepalived:2.2.4
